[pytest]
asyncio_mode = auto
testpaths = tests
filterwarnings =
    error::DeprecationWarning
    error::ResourceWarning
    error::starlette.exceptions.StarletteDeprecationWarning
    ignore:Support for class-based `config` is deprecated, use ConfigDict instead.*:pydantic.warnings.PydanticDeprecatedSince20
    ignore:The anyio.abc.BlockingPortal alias is deprecated, use anyio.from_thread.BlockingPortal instead.*:DeprecationWarning:starlette.testclient
